# Generated by Django 2.1.7 on 2019-06-09 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='描述')),
                ('votes', models.IntegerField(default=0, editable=False, verbose_name='投票数')),
                ('file', models.FileField(default=None, null=True, upload_to='', verbose_name='文件')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='图片')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 6, 9, 23, 42, 31, 99313), verbose_name='发布时间')),
                ('days_of_born', models.IntegerField(editable=False, verbose_name='出生天数')),
            ],
        ),
    ]
