# Generated by Django 2.1.7 on 2019-06-09 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 23, 44, 7, 555914), verbose_name='发布时间'),
        ),
    ]
