# Generated by Django 2.1.7 on 2019-06-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYE', '0004_auto_20190611_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 0, 52, 0, 903978), verbose_name='发布时间'),
        ),
    ]
