# Generated by Django 2.1.7 on 2019-06-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYE', '0005_auto_20190611_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 0, 54, 28, 648304), verbose_name='发布时间'),
        ),
    ]
