# Generated by Django 2.1.7 on 2019-06-10 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYE', '0006_auto_20190611_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 1, 9, 7, 858519), verbose_name='发布时间'),
        ),
    ]
