# Generated by Django 2.1.7 on 2019-12-21 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYE', '0009_auto_20191128_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='描述')),
                ('votes', models.IntegerField(default=0, editable=False, verbose_name='投票数')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='文件')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 12, 21, 23, 39, 32, 274605), verbose_name='发布时间')),
                ('days_of_born', models.IntegerField(editable=False, verbose_name='出生天数')),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 23, 39, 32, 250611), verbose_name='发布时间'),
        ),
    ]
